### PR TITLE
refactor(tooltip): tooltip-v2 - aligned to how popover functions

### LINKED ISSUE #175: [Primitive] Tooltip: onscroll & changing trigger position behaviour (when open state is controlled)
### Overview

The tooltip must be pinned to `tooltipTrigger` when page is scrolling or tooltipTrigger position changed.
This beahviour must by applied only in case when open state is cotrolled.

### Examples in other libraries

https://codesandbox.io/p/devbox/interesting-resonance-d3rrsc?workspaceId=ws_YF21hxMA1PrVmn99UMB9gU

### PR DESCRIPTION
**Pull request by pawel-twardziak**
Closes #175 

@pimenovoleg @mrfrac @artembelik 
This is an RC version of `tooltip`-v2 ready to have a lot in common with `popover`. Works perfect :)
Once you approve it, I will remove the current `tooltip` and rename `tooltip`-v2 to `tooltip`

CAUTION: I've left `CloseDirective` as it works fine with external triggering enabled. Just to showcase - can be removed.

https://github.com/user-attachments/assets/1de2653c-60c3-4633-9c9b-6bc5889a2183

### CODE REVIEW

**Comment by pimenovoleg** [comment]
Nice, this version came out super quickly! :)

While reviewing the examples, I noticed a strange indentation here. Is everything okay with it?
In `multiple` section, secondary example.

image

**Comment by pawel-twardziak** [comment]
> Nice, this version came out super quickly! :)
> 
> While reviewing the examples, I noticed a strange indentation here. Is everything okay with it? In `multiple` section, secondary example.
>

@pimenovoleg yes, that's ok because the second and the third of the multiple case story have side offset and align offset applied. Maybe I should add an info about it to them, what do you thing? You feel confused w/o that info so the other can also feel the same, I think :)

**Comment by pawel-twardziak** [comment]
> Nice, this version came out super quickly! :)
> 
> While reviewing the examples, I noticed a strange indentation here. Is everything okay with it? In `multiple` section, secondary example.
>

@pimenovoleg yes, that's ok because the second and the third of the multiple case story have side offset and align offset applied. Maybe I should add an info about it to them, what do you thing? You feel confused w/o that info so the other can also feel the same, I think :)

**Comment by pawel-twardziak** [comment]
@pimenovoleg 
would this be ok? 
obraz

**Comment by pawel-twardziak** [comment]
btw @pimenovoleg when I click deployment vercel links I see this:
obraz

It would be nice to have an access but w/o it is also ok :)

**Comment by pimenovoleg** [comment]
> > Nice, this version came out super quickly! :)
> > While reviewing the examples, I noticed a strange indentation here. Is everything okay with it? In `multiple` section, secondary example.
> 
> @pimenovoleg yes, that's ok because the second and the third of the multiple case story have side offset and align offset applied. Maybe I should add an info about it to them, what do you thing? You feel confused w/o that info so the other can also feel the same, I think :)

Yes, I think adding some information about the side and align offsets would be really helpful. It makes the examples more self-explanatory, especially for someone reviewing them for the first time. Maybe a short comment or a note in the documentation near the example would work well. What do you think? 😊

**Comment by pawel-twardziak** [comment]
> Yes, I think adding some information about the side and align offsets would be really helpful. It makes the examples more self-explanatory, especially for someone reviewing them for the first time. Maybe a short comment or a note in the documentation near the example would work well. What do you think? 😊

Yes, I definitely agree :)

What about this:

> @pimenovoleg would this be ok? obraz

Make sense? :)

**Comment by pimenovoleg** [comment]
> btw @pimenovoleg when I click deployment vercel links I see this: obraz
> 
> It would be nice to have an access but w/o it is also ok :)

I changed some settings, please try creating a PR from a branch instead of a fork next time.

**Comment by pawel-twardziak** [comment]
@pimenovoleg can I continue on this by removing the current tiiltip and replacing it with the v2? Then I wanna create `hover card` and next that one https://github.com/radix-ng/primitives/issues/236

**Comment by pimenovoleg** [comment]
> @pimenovoleg can I continue on this by removing the current tiiltip and replacing it with the v2? Then I wanna create `hover card` and next that one #236

lets do it 👍

**Comment by pawel-twardziak** [comment]
@pimenovoleg ready to CR

**Pull request merged**
